### ISSUE TITLE
Needs to be more explicit with compatible AMD GPUs

### ISSUE THREAD

**Issue by Zeglius** [KyleGospo/docs.bazzite.gg#11]
Some folks commented in Discord that "A modern AMD GPU" is not explicit enough.

https://github.com/KyleGospo/docs.bazzite.gg/blob/a1176785de73529caabbeb7da8e580787f9ac5de/src/Gaming/Hardware_compatibility_for_gaming.md?plain=1#L25

Perhaps something like "AMD GPU newer than Polaris" would be enough, though would be nice to have an hyperlink that points to some reference/resource where they can check at quick glance

**Comment by nicknamenamenick** [comment]
AMD Polaris hardware might not have as many caveats supposedly.
