### ISSUE TITLE
Contribution pages restructuring

### ISSUE THREAD

**Issue by Zeglius** [KyleGospo/docs.bazzite.gg#21]
Right now, it seems like a mix-up of universal blue and bazzite. We will need to separate it, leaving only bazzite specific parts, universal blue could be linked elsewhere.
We need to avoid information redundancy.

**Comment by nicknamenamenick** [comment]
This will probably conflict with @castrojo.  He wants the contributing guidelines to stay nearly identical to Universal Blue regardless.

**Comment by castrojo** [comment]
Yeah I am questioning the value of centralized ublue docs, so might be best to just diverge? Dunno, plusses and minuses to both.

**Comment by Zeglius** [comment]
> This will probably conflict with @castrojo.  He wants the contributing guidelines to stay nearly identical to Universal Blue regardless.

Then what we can do is split in two separate subpages, one with the bazzite specific bits and other with more general universal blue.

**Comment by Zeglius** [comment]
Though now that I think of it, a simple block quote mentioning that the page is not only aimed to bazzite, but ublue as well, might suffice. 

I'm probably overthinking with this issue. My apologies.

**Comment by nicknamenamenick** [comment]
> I'm probably overthinking with this issue.  My apologies.

Don't apologize 😄 that's what we do here!  It's good to get this all figured out by thinking outside the box.
